// Literal Tailwind v4 utilities. Group markers preserve descendant styling without CSS modules.
const styles = {
  "sample": "group/e-sample [&]:col-[5_/_-1] [&]:min-w-[0] [&]:pt-[3px] max-[767.01px]:[&]:col-[1]",
  "sampleHeader": "group/e-sampleHeader [&]:flex [&]:items-center [&]:justify-between [&]:gap-[16px] [&]:mb-[22px] [&]:text-[var(--muted)] [&]:text-[0.8125rem] [&_code]:text-[0.8125rem] [&_code]:text-[var(--body)]",
  "comparison": "group/e-comparison [&]:grid [&]:grid-cols-[1fr_1fr] [&]:border-y-[1px] [&]:border-solid [&]:border-y-[var(--control-border)]",
  "sampleValue": "group/e-sampleValue [&]:min-w-[0] [&]:pt-[22px] [&]:pr-[20px] [&]:pb-[36px] [&]:pl-[0] [&_+_[class~='group/e-sampleValue']]:border-l-[1px] [&_+_[class~='group/e-sampleValue']]:border-solid [&_+_[class~='group/e-sampleValue']]:border-l-[var(--hairline)] [&_+_[class~='group/e-sampleValue']]:pl-[28px] [&_+_[class~='group/e-sampleValue']]:pr-[0] [&_h3]:flex [&_h3]:flex-wrap [&_h3]:justify-between [&_h3]:gap-[6px_16px] [&_h3]:mb-[40px] [&_h3]:text-[var(--body)] [&_h3]:text-[0.875rem] [&_h3]:font-[500] [&_h3_span]:text-[var(--muted)] [&_h3_span]:font-[400] [&_h3_span]:text-[0.8125rem] [&_p]:mt-[0] [&_p]:mr-[0] [&_p]:mb-[0] [&_p]:ml-[0] [&_p]:text-[var(--ink)] [&_p]:wrap-anywhere [&_code]:text-[clamp(1rem,_1.45vw,_1.25rem)] [&_code]:leading-[1.8] [&_mark]:pb-[4px] [&_mark]:bg-[transparent] [&_mark]:border-b-[3px] [&_mark]:border-solid [&_mark]:border-b-[var(--primary)] [&_mark]:text-[inherit] [&_mark]:whitespace-nowrap max-[1100.01px]:[&_h3]:block max-[1100.01px]:[&_h3_span]:block max-[1100.01px]:[&_h3_span]:mt-[5px] max-[767.01px]:[&]:pt-[18px] max-[767.01px]:[&]:pb-[28px] max-[767.01px]:[&]:pr-[16px] max-[767.01px]:[&_+_[class~='group/e-sampleValue']]:pl-[16px] max-[767.01px]:[&_h3]:mb-[28px] max-[767.01px]:[&_code]:text-[1rem] max-[380.01px]:[&_code]:text-[0.875rem]",
  "sampleControls": "group/e-sampleControls [&]:flex [&]:items-center [&]:flex-wrap [&]:gap-[8px_24px] [&]:mt-[24px] max-[767.01px]:[&]:gap-[8px_20px] max-[380.01px]:[&]:items-stretch",
  "runButton": "group/e-runButton [&]:inline-flex [&]:items-center [&]:justify-between [&]:gap-[20px] [&]:min-w-[168px] [&]:min-h-[46px] [&]:pt-[10px] [&]:pr-[14px] [&]:pb-[10px] [&]:pl-[14px] [&]:bg-[var(--ink)] [&]:text-[var(--canvas)] [&]:border-[1px] [&]:border-solid [&]:border-[var(--ink)] [&]:rounded-[4px] [&]:font-[500] [&]:transition-[background-color] [&]:duration-[var(--duration-feedback)] [&]:ease-[var(--ease-feedback)] [&:disabled]:border-[var(--primary-disabled)] [&:disabled]:cursor-progress [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover:not(:disabled)]:bg-[var(--body)] max-[380.01px]:[&]:flex-[1] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&_svg]:transition-[transform] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&_svg]:duration-[var(--duration-enter)] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&_svg]:ease-[var(--ease-out)] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&:not(:disabled):not(:focus-visible):hover_svg]:translate-x-[2px] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&:not(:disabled):not(:focus-visible):active_svg]:translate-x-[0] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&:not(:disabled):not(:focus-visible):active_svg]:duration-[var(--duration-feedback)] [@media_(prefers-reduced-motion:_reduce)]:[&]:transition-none",
  "restoreButton": "group/e-restoreButton [&]:border-0 [&]:rounded-[0] [&]:pt-[10px] [&]:pr-[0] [&]:pb-[10px] [&]:pl-[0] [&]:text-[var(--link)] [&]:bg-[transparent] [&]:text-[0.875rem] [&]:underline [&]:underline-offset-[5px] [&]:decoration-[var(--control-border)] [&[aria-pressed='true']]:text-[var(--body)] [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover]:decoration-[currentColor]",
  "sampleFeedback": "group/e-sampleFeedback [&]:min-h-[126px] [&]:pt-[24px] [&]:pb-[12px] [&_p]:mt-[0] [&_p]:mr-[0] [&_p]:mb-[0] [&_p]:ml-[0] [&_p]:text-[var(--muted)] [&_p]:text-[0.875rem] [&_p]:leading-[1.65] [&[data-outcome='pass']_strong]:text-[var(--success)] [&[data-outcome='fail']_strong]:text-[var(--error)] [&_[class~='group/e-sampleError']]:text-[var(--error)] starting:[&[data-motion='pointer']_[class~='group/e-liveResult']]:opacity-[0] max-[767.01px]:[&]:min-h-[136px]",
  "liveResult": "group/e-liveResult [&]:opacity-[1] [&]:transition-[opacity] [&]:duration-[var(--duration-enter)] [&]:ease-[var(--ease-out)] [&_strong]:block [&_strong]:mb-[7px] [&_strong]:text-[var(--ink)] [&_strong]:font-[500] [&_strong]:text-[0.9375rem] [@media_(prefers-reduced-motion:_reduce)]:[&]:transition-none",
  "responseVersion": "group/e-responseVersion [&]:block [&]:mt-[9px] [&]:text-[var(--muted)] [&]:text-[0.75rem]",
  "sampleLink": "group/e-sampleLink [&]:inline-flex [&]:items-center [&]:gap-[16px] [&]:min-h-[44px] [&]:text-[var(--link)] [&]:text-[0.875rem] [&]:underline-offset-[5px] [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover]:decoration-[currentColor] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&_svg]:transition-[transform] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&_svg]:duration-[var(--duration-enter)] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&_svg]:ease-[var(--ease-out)] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&:not(:focus-visible):hover_svg]:translate-x-[1px] [@media_(hover:_hover)_and_(pointer:_fine)_and_(prefers-reduced-motion:_no-preference)]:[&:not(:focus-visible):hover_svg]:translate-y-[-1px]",
  "sampleError": "group/e-sampleError"
} as const;

export default styles;
