// Literal Tailwind v4 utilities. Group markers preserve descendant styling without CSS modules.
const styles = {
  "list": "group/l-list [&]:grid [&]:gap-[20px] [&]:min-w-[0] [&]:font-[family-name:var(--font-ui,_'IBM_Plex_Sans',_system-ui,_sans-serif)]",
  "toolbar": "group/l-toolbar [&]:flex [&]:items-center [&]:justify-between [&]:flex-wrap [&]:gap-[12px] [&]:pb-[4px] [&_p]:text-[15px] max-[600.01px]:[&]:items-start",
  "results": "group/l-results [&]:flex [&]:items-center [&]:justify-between [&]:flex-wrap [&]:gap-[12px] [&]:min-h-[44px] [&]:pb-[12px] [&]:text-[var(--muted)] [&]:text-[13px] [&]:tabular-nums",
  "newTask": "group/l-newTask [&]:min-w-[132px]",
  "filters": "group/l-filters [&]:grid [&]:grid-cols-[minmax(200px,_1fr)_minmax(150px,_.55fr)_minmax(190px,_.65fr)_auto] [&]:items-end [&]:gap-[12px] max-[1100.01px]:[&]:grid-cols-[repeat(2,_minmax(0,_1fr))] max-[600.01px]:[&]:grid-cols-[minmax(0,_1fr)]",
  "field": "group/l-field [&]:grid [&]:gap-[8px] [&]:min-w-[0] [&]:text-[var(--body)] [&]:text-[13px] [&]:font-[500] [&_input]:w-[100%] [&_input]:min-w-[0] [&_input]:min-h-[44px] [&_input]:pt-[10px] [&_input]:pr-[12px] [&_input]:pb-[10px] [&_input]:pl-[12px] [&_input]:border-[1px] [&_input]:border-solid [&_input]:border-[var(--control-border)] [&_input]:rounded-[var(--radius-sm)] [&_input]:bg-[var(--canvas)] [&_input]:text-[var(--ink)] [&_input]:text-[16px] [&_input]:font-[400] [&_input]:leading-[1.4] [&_select]:w-[100%] [&_select]:min-w-[0] [&_select]:min-h-[44px] [&_select]:pt-[10px] [&_select]:pr-[12px] [&_select]:pb-[10px] [&_select]:pl-[12px] [&_select]:border-[1px] [&_select]:border-solid [&_select]:border-[var(--control-border)] [&_select]:rounded-[var(--radius-sm)] [&_select]:bg-[var(--canvas)] [&_select]:text-[var(--ink)] [&_select]:text-[16px] [&_select]:font-[400] [&_select]:leading-[1.4] [&_input::placeholder]:text-[var(--muted)] [&_input::placeholder]:opacity-[1]",
  "searchInput": "group/l-searchInput [&]:relative [&]:block [&_>_svg]:absolute [&_>_svg]:left-[12px] [&_>_svg]:top-[12px] [&_>_svg]:text-[var(--muted)] [&_>_svg]:pointer-events-none [&_input]:pl-[40px]",
  "refresh": "group/l-refresh [&]:min-w-[148px] max-[1100.01px]:[&]:col-[1_/_-1] max-[1100.01px]:[&]:justify-self-start",
  "scope": "group/l-scope [&]:grid [&]:gap-[8px] [&]:text-[var(--muted)] [&]:text-[13px] [&_p]:max-w-[none]",
  "limit": "group/l-limit [&]:flex [&]:items-start [&]:gap-[8px] [&]:text-[var(--warning)] [&_svg]:shrink-[0]",
  "footnote": "group/l-footnote [&_svg]:shrink-[0] [&_svg]:w-[16px] [&_svg]:h-[16px] [&_svg]:mt-[2px] [&]:flex [&]:items-start [&]:gap-[8px] [&]:text-[var(--muted)] [&]:text-[12px] [&]:leading-[1.6]",
  "error": "group/l-error [&]:justify-items-start",
  "clear": "group/l-clear [&]:min-h-[44px] [&]:pt-[8px] [&]:pr-[0] [&]:pb-[8px] [&]:pl-[0] [&]:border-0 [&]:bg-[transparent] [&]:text-[var(--link)] [&]:text-[13px]! [&]:underline [&]:underline-offset-[4px] [&]:cursor-pointer [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover]:decoration-[2px] [&:active]:text-[var(--ink)]",
  "columns": "group/l-columns [&]:grid [&]:grid-cols-[minmax(0,_1.6fr)_minmax(0,_1fr)_minmax(0,_1fr)_minmax(0,_1.1fr)_20px] [&]:gap-x-[20px] [&]:pt-[12px] [&]:pr-[8px] [&]:pb-[12px] [&]:pl-[8px] [&]:border-y-[1px] [&]:border-solid [&]:border-y-[var(--hairline)] [&]:text-[var(--muted)] [&]:text-[12px] [&]:font-[500] max-[1100.01px]:[&]:grid-cols-[minmax(0,_1.3fr)_minmax(0,_1fr)_minmax(0,_1fr)_20px] max-[1100.01px]:[&]:gap-x-[16px] max-[1100.01px]:[&_>_:nth-child(2)]:hidden max-[600.01px]:[&]:hidden",
  "taskRow": "group/l-taskRow [&]:grid [&]:grid-cols-[minmax(0,_1.6fr)_minmax(0,_1fr)_minmax(0,_1fr)_minmax(0,_1.1fr)_20px] [&]:gap-x-[20px] [&]:relative [&]:items-center [&]:pt-[20px] [&]:pr-[8px] [&]:pb-[20px] [&]:pl-[8px] [&]:border-b-[1px] [&]:border-solid [&]:border-b-[var(--hairline)] [&]:text-[var(--body)] [&]:no-underline [&]:transition-[background-color] [&]:duration-[var(--duration-feedback)] [&]:ease-[var(--ease-feedback)] [&_>_div]:min-w-[0] [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover]:bg-[var(--surface-soft)] [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover_[class~='group/l-taskTitle']]:underline [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover_[class~='group/l-taskTitle']]:underline-offset-[4px] [@media_(hover:_hover)_and_(pointer:_fine)]:[&:hover_[class~='group/l-rowArrow']]:text-[var(--link)] [&:active]:bg-[var(--surface-card)] [&:focus-visible]:z-[1] [&:focus-visible]:outline-offset-[-2px] [&:focus-visible]:bg-[var(--surface-soft)] max-[1100.01px]:[&]:grid-cols-[minmax(0,_1.3fr)_minmax(0,_1fr)_minmax(0,_1fr)_20px] max-[1100.01px]:[&]:gap-x-[16px] max-[600.01px]:[&]:grid-cols-[minmax(0,_1fr)_minmax(0,_1fr)_20px] max-[600.01px]:[&]:gap-[16px_12px] [@media_(prefers-reduced-motion:_reduce)]:[&]:transition-none",
  "taskList": "group/l-taskList [&]:list-none [&]:mt-[0] [&]:mr-[0] [&]:mb-[0] [&]:ml-[0] [&]:pt-[0] [&]:pr-[0] [&]:pb-[0] [&]:pl-[0] max-[600.01px]:[&]:border-t-[1px] max-[600.01px]:[&]:border-solid max-[600.01px]:[&]:border-t-[var(--hairline)]",
  "taskSummary": "group/l-taskSummary [&]:grid [&]:gap-[4px] [&_[class~='group/l-meta']_code]:text-[12px] max-[600.01px]:[&]:col-[1_/_3]",
  "counterparty": "group/l-counterparty [&]:grid [&]:gap-[4px] [&_code]:text-[12px] [&_code]:wrap-anywhere max-[1100.01px]:[&]:col-[1] max-[1100.01px]:[&]:row-[2] max-[1100.01px]:[&]:mt-[8px] max-[600.01px]:[&]:col-[1_/_3] max-[600.01px]:[&]:row-[2] max-[600.01px]:[&]:mt-[0]",
  "deadline": "group/l-deadline [&]:grid [&]:gap-[4px] [&_time]:text-[13px] [&_time]:tabular-nums max-[1100.01px]:[&]:col-[2] max-[1100.01px]:[&]:row-[1_/_3] max-[600.01px]:[&]:col-[1] max-[600.01px]:[&]:row-[3] max-[600.01px]:[&]:self-start",
  "rowStatus": "group/l-rowStatus [&]:grid [&]:gap-[6px] max-[1100.01px]:[&]:col-[3] max-[1100.01px]:[&]:row-[1_/_3] max-[600.01px]:[&]:col-[2_/_4] max-[600.01px]:[&]:row-[3] max-[600.01px]:[&]:self-start",
  "taskTitle": "group/l-taskTitle [&]:text-[var(--ink)] [&]:text-[16px] [&]:font-[500] [&]:leading-[1.4] [&]:wrap-anywhere",
  "meta": "group/l-meta [&]:text-[var(--muted)] [&]:text-[13px]",
  "mobileLabel": "group/l-mobileLabel [&]:text-[var(--muted)] [&]:text-[13px] [&]:absolute [&]:w-[1px] [&]:h-[1px] [&]:pt-[0] [&]:pr-[0] [&]:pb-[0] [&]:pl-[0] [&]:mt-[-1px] [&]:mr-[-1px] [&]:mb-[-1px] [&]:ml-[-1px] [&]:overflow-hidden [&]:sr-only [&]:whitespace-nowrap max-[600.01px]:[&]:static max-[600.01px]:[&]:w-[auto] max-[600.01px]:[&]:h-[auto] max-[600.01px]:[&]:mt-[0] max-[600.01px]:[&]:mr-[0] max-[600.01px]:[&]:mb-[0] max-[600.01px]:[&]:ml-[0] max-[600.01px]:[&]:overflow-visible max-[600.01px]:[&]:not-sr-only max-[600.01px]:[&]:whitespace-normal",
  "rowArrow": "group/l-rowArrow [&]:text-[var(--muted)] max-[1100.01px]:[&]:col-[4] max-[1100.01px]:[&]:row-[1_/_3] max-[600.01px]:[&]:col-[3] max-[600.01px]:[&]:row-[1] max-[600.01px]:[&]:self-start",
  "empty": "group/l-empty [&]:grid [&]:justify-items-start [&]:content-start [&]:gap-[12px] [&]:pt-[40px] [&]:pr-[8px] [&]:pb-[40px] [&]:pl-[8px] [&]:border-y-[1px] [&]:border-solid [&]:border-y-[var(--hairline)] [&_>_svg]:text-[var(--muted)] [&_>_svg]:mb-[4px] [&_p]:text-[var(--muted)] [&_p]:text-[14px] [&_a]:gap-[8px] max-[600.01px]:[&]:pt-[32px] max-[600.01px]:[&]:pb-[32px]",
  "search": "group/l-search max-[1100.01px]:[&]:col-[1_/_-1]"
} as const;

export default styles;
